// --- DATA & CONSTANTS ---
const classData = { 
	amazon: { stats: { str: 14, dex: 14, con: 16, int: 10, wis: 14, cha: 16 }, 
		skills: {
			bows: {},
			javelins: {},
			passive: {}
		} }, 
	assassin: { stats: { str: 14, dex: 14, con: 16, int: 10, wis: 14, cha: 16 },
		skills: {
			martial: {},
			shadow: {},
			traps: {}
		} }, 
	barbarian: { stats: { str: 18, dex: 13, con: 17, int: 8, wis: 10, cha: 11 },
		skills: {
			warcries: {},
			weapons: {},
			combat: {}
		} },  
	druid: { stats: { str: 14, dex: 14, con: 16, int: 10, wis: 14, cha: 16 },
		skills: {
			elemental: {},
			shapeshifting: {},
			combat: {}
		} }, 
	necromancer: { stats: { str: 14, dex: 14, con: 16, int: 10, wis: 14, cha: 16 }, 
		skills: {
			summoning: {},
			poison: {},
			curses: {}
		} },
	paladin: { stats: { str: 14, dex: 14, con: 16, int: 10, wis: 14, cha: 16 }, 
		skills: {
			offensive: {},
			defensive: {},
			combat: {}
		} },
	sorceress: { stats: { str: 8, dex: 12, con: 10, int: 18, wis: 16, cha: 14 }, 
		skills: {
			fire: {},
			cold: {},
			lightning: {}
		} } };
	
const itemDatabase = {
	// Body Armor
	'quilted_armor': { name: 'Quilted Armor', w: 2, h: 3, color: 'bg-gray-800', type: 'body', category: 'armor', 
		stats: { ac: 1, weight: 'Light' }, img: 'assets/armor/quilted.gif' },
	'leather_armor': { name: 'Leather Armor', w: 2, h: 3, color: 'bg-yellow-900', type: 'body', category: 'armor', 
		stats: { ac: 2, weight: 'Light' }, img: 'assets/armor/leather.gif'  },
	'hard_leather_armor': { name: 'Hard Leather Armor', w: 2, h: 3, color: 'bg-yellow-800', type: 'body', category: 'armor', 
		stats: { ac: 3, weight: 'Light' }, img: 'assets/armor/hardleather.gif'  },
	'studded_leather': { name: 'Studded Leather', w: 2, h: 3, color: 'bg-gray-700', type: 'body', category: 'armor', 
		stats: { ac: 4, weight: 'Medium' }, img: 'assets/armor/studdedleather.gif' },
	'ring_mail': { name: 'Ring Mail', w: 2, h: 3, color: 'bg-gray-600', type: 'body', category: 'armor', 
		stats: { ac: 4, weight: 'Light' }, img: 'assets/armor/ringmail.gif'  },
	'scale_mail': { name: 'Scale Mail', w: 2, h: 3, color: 'bg-gray-500', type: 'body', category: 'armor', 
		stats: { ac: 5, weight: 'Heavy' }, img: 'assets/armor/scalemail.gif'  },
	'chain_mail': { name: 'Chain Mail', w: 2, h: 3, color: 'bg-gray-600', type: 'body', category: 'armor', 
		stats: { ac: 5, weight: 'Medium' }, img: 'assets/armor/chainmail.gif'  },
	'breast_plate': { name: 'Breast Plate', w: 2, h: 3, color: 'bg-gray-400', type: 'body', category: 'armor', 
		stats: { ac: 5, weight: 'Light' }, img: 'assets/armor/breastplate.png'  },
	'splint_mail': { name: 'Splint Mail', w: 2, h: 3, color: 'bg-gray-800', type: 'body', category: 'armor', 
		stats: { ac: 6, weight: 'Medium' }, img: 'assets/armor/splintmail.gif'  },
	'plate_mail': { name: 'Plate Mail', w: 2, h: 3, color: 'bg-gray-400', type: 'body', category: 'armor', 
		stats: { ac: 7, weight: 'Heavy' }, img: 'assets/armor/platemail.gif'  },
	'field_plate': { name: 'Field Plate', w: 2, h: 3, color: 'bg-gray-300', type: 'body', category: 'armor', 
		stats: { ac: 7, weight: 'Medium' }, img: 'assets/armor/fieldplate.gif'  },
	'gothic_plate': { name: 'Gothic Plate', w: 2, h: 3, color: 'bg-gray-200', type: 'body', category: 'armor', 
		stats: { ac: 8, weight: 'Medium' }, img: 'assets/armor/gothicplate.gif'  },
	'light_plate': { name: 'Light Plate', w: 2, h: 3, color: 'bg-gray-100', type: 'body', category: 'armor', 
		stats: { ac: 8, weight: 'Light' }, img: 'assets/armor/lightplate.gif'  },
	'full_plate_mail': { name: 'Full Plate Mail', w: 2, h: 3, color: 'bg-white', type: 'body', category: 'armor', 
		stats: { ac: 9, weight: 'Heavy' }, img: 'assets/armor/fullplate.gif'  },
	'ancient_armor': { name: 'Ancient Armor', w: 2, h: 3, color: 'bg-yellow-200', type: 'body', category: 'armor', 
		stats: { ac: 10, weight: 'Medium' }, img: 'assets/armor/ancientarmor.gif'  },

	// Helms
	'cap': { name: 'Cap', w: 2, h: 2, color: 'bg-yellow-800', type: 'head', category: 'helms', 
		stats: { ac: 1 }, img: 'assets/armor/helms/cap.gif'  },
	'skull_cap': { name: 'Skull Cap', w: 2, h: 2, color: 'bg-gray-300', type: 'head', category: 'helms', 
		stats: { ac: 2 }, img: 'assets/armor/helms/skullcap.gif'  },
	'helm': { name: 'Helm', w: 2, h: 2, color: 'bg-gray-700', type: 'head', category: 'helms', 
		stats: { ac: 3 }, img: 'assets/armor/helms/helm.gif'  },
	'mask': { name: 'Mask', w: 2, h: 2, color: 'bg-yellow-600', type: 'head', category: 'helms', 
		stats: { ac: 3 }, img: 'assets/armor/helms/mask.gif'  },
	'full_helm': { name: 'Full Helm', w: 2, h: 2, color: 'bg-gray-600', type: 'head', category: 'helms', 
		stats: { ac: 4 }, img: 'assets/armor/helms/fullhelm.gif'  },
	'bone_helm': { name: 'Bone Helm', w: 2, h: 2, color: 'bg-gray-200', type: 'head', category: 'helms', 
		stats: { ac: 5 }, img: 'assets/armor/helms/bonehelm.gif'  },
	'great_helm': { name: 'Great Helm', w: 2, h: 2, color: 'bg-gray-500', type: 'head', category: 'helms', 
		stats: { ac: 5 }, img: 'assets/armor/helms/greathelm.gif'  },
	'crown': { name: 'Crown', w: 2, h: 2, color: 'bg-yellow-500', type: 'head', category: 'helms', 
		stats: { ac: 5 }, img: 'assets/armor/helms/crown.gif'  },
		//TODO: add unique helms and circlets
	'circlet': { name: 'Circlet', w: 2, h: 1, color: 'bg-yellow-400', type: 'head', category: 'helms', 
		stats: { ac: 6 }, img: 'assets/armor/helms/circlet.gif'  },

	// Shields
	'buckler': { name: 'Buckler', w: 2, h: 2, color: 'bg-yellow-900', type: 'offhand', category: 'shields', 
		stats: { ac: 1, weight: 'Light' }, img: 'assets/armor/shields/buckler.gif'  },
	'small_shield': { name: 'Small Shield', w: 2, h: 2, color: 'bg-yellow-800', type: 'offhand', category: 'shields', 
		stats: { ac: 2, weight: 'Light' }, img: 'assets/armor/shields/smallshield.gif'  },
	'large_shield': { name: 'Large Shield', w: 2, h: 3, color: 'bg-yellow-700', type: 'offhand', category: 'shields', 
		stats: { ac: 3, weight: 'Light' }, img: 'assets/armor/shields/largeshield.gif'  },
	'spiked_shield': { name: 'Spiked Shield', w: 2, h: 2, color: 'bg-gray-500', type: 'offhand', category: 'shields', 
		stats: { ac: 3, weight: 'Light' }, img: 'assets/armor/shields/spikedshield.gif'  },
	'kite_shield': { name: 'Kite Shield', w: 2, h: 3, color: 'bg-blue-300', type: 'offhand', category: 'shields', 
		stats: { ac: 4, weight: 'Light' }, img: 'assets/armor/shields/kiteshield.gif'  },
	'bone_shield': { name: 'Bone Shield', w: 2, h: 3, color: 'bg-gray-200', type: 'offhand', category: 'shields', 
		stats: { ac: 5, weight: 'Light' }, img: 'assets/armor/shields/boneshield.gif'  },
	'tower_shield': { name: 'Tower Shield', w: 2, h: 3, color: 'bg-gray-500', type: 'offhand', category: 'shields', 
		stats: { ac: 6, weight: 'Heavy' }, img: 'assets/armor/shields/towershield.gif'  },
	'gothic_shield': { name: 'Gothic Shield', w: 2, h: 3, color: 'bg-red-800', type: 'offhand', category: 'shields', 
		stats: { ac: 6, weight: 'Medium' }, img: 'assets/armor/shields/gothicshield.gif'  },
		//TODO: add unique shields

	// Swords
	'shortsword': { name: 'Shortsword', w: 1, h: 3, color: 'bg-blue-200', type: 'hand', category: 'swords', stats: { dmg: 'D4', speed: 'Fast' }, img: 'assets/weapons/swords/shortsword.gif' },
	'scimitar': { name: 'Scimitar', w: 1, h: 3, color: 'bg-blue-300', type: 'hand', category: 'swords', stats: { dmg: 'D4', speed: 'Very Fast' }, img: 'assets/weapons/swords/scimitar.gif' },
	'saber': { name: 'Saber', w: 1, h: 3, color: 'bg-blue-400', type: 'hand', category: 'swords', stats: { dmg: 'D6', speed: 'Fast' }, img: 'assets/weapons/swords/saber.gif' },
	'crystal_sword': { name: 'Crystal Sword', w: 1, h: 3, color: 'bg-blue-100', type: 'hand', category: 'swords', stats: { dmg: 'D8', speed: 'Fast' }, img: 'assets/weapons/swords/crystalsword.gif' },
	'falchion': { name: 'Falchion', w: 1, h: 3, color: 'bg-blue-500', type: 'hand', category: 'swords', stats: { dmg: 'D10', speed: 'Slow' }, img: 'assets/weapons/swords/falchion.gif' },
	'broadsword': { name: 'Broadsword', w: 2, h: 3, color: 'bg-blue-600', type: 'hand', category: 'swords', stats: { dmg: 'D10', speed: 'Fast' }, img: 'assets/weapons/swords/broadsword.gif' },
	'longsword': { name: 'Longsword', w: 2, h: 3, color: 'bg-blue-700', type: 'hand', category: 'swords', stats: { dmg: 'D12', speed: 'Fast' }, img: 'assets/weapons/swords/longsword.gif' },
	'two_handed_sword': { name: 'Two Handed Sword', w: 2, h: 4, color: 'bg-blue-800', type: 'hand', category: 'swords', stats: { dmg: 'D4/D8', speed: 'Fast' }, img: 'assets/weapons/swords/twohanded.gif' },
	'claymore': { name: 'Claymore', w: 2, h: 4, color: 'bg-blue-900', type: 'hand', category: 'swords', stats: { dmg: 'D6/D10', speed: 'Normal' }, img: 'assets/weapons/swords/claymore.gif' },
	'giant_sword': { name: 'Giant Sword', w: 2, h: 4, color: 'bg-blue-800', type: 'hand', category: 'swords', stats: { dmg: 'D6/D10', speed: 'Fast' }, img: 'assets/weapons/swords/giantsword.gif' },
	'bastard_sword': { name: 'Bastard Sword', w: 2, h: 4, color: 'bg-blue-700', type: 'hand', category: 'swords', stats: { dmg: 'D8/D12', speed: 'Normal' }, img: 'assets/weapons/swords/bastardsword.gif' },
	'flamberge': { name: 'Flamberge', w: 2, h: 4, color: 'bg-blue-600', type: 'hand', category: 'swords', stats: { dmg: 'D8/D12', speed: 'Fast' }, img: 'assets/weapons/swords/flamberge.gif' },
	'war_sword': { name: 'War Sword', w: 2, h: 4, color: 'bg-blue-500', type: 'hand', category: 'swords', stats: { dmg: 'D10/D12', speed: 'Fast' }, img: 'assets/weapons/swords/warsword.gif' },
	'great_sword': { name: 'Great Sword', w: 2, h: 4, color: 'bg-blue-400', type: 'hand', category: 'swords', stats: { dmg: 'D10/D20', speed: 'Normal' }, img: 'assets/weapons/swords/greatsword.gif' },

	// Axes
	'hand_axe': { name: 'Hand Axe', w: 2, h: 3, color: 'bg-gray-400', type: 'hand', category: 'axes', stats: { dmg: 'D4', speed: 'Fast' }, img: 'assets/weapons/axes/handaxe.gif' },
	'large_axe': { name: 'Large Axe', w: 2, h: 3, color: 'bg-gray-500', type: 'hand', category: 'axes', stats: { dmg: 'D6', speed: 'Slow' }, img: 'assets/weapons/axes/largeaxe.gif' },
	'axe': { name: 'Axe', w: 2, h: 3, color: 'bg-gray-400', type: 'hand', category: 'axes', stats: { dmg: 'D6', speed: 'Normal' }, img: 'assets/weapons/axes/axe.gif' },
	'broad_axe': { name: 'Broad Axe', w: 2, h: 3, color: 'bg-gray-500', type: 'hand', category: 'axes', stats: { dmg: 'D8', speed: 'Normal' }, img: 'assets/weapons/axes/broadaxe.gif' },
	'double_axe': { name: 'Double Axe', w: 2, h: 3, color: 'bg-gray-400', type: 'hand', category: 'axes', stats: { dmg: 'D10', speed: 'Normal' }, img: 'assets/weapons/axes/doubleaxe.gif' },
	'battle_axe': { name: 'Battle Axe', w: 2, h: 3, color: 'bg-gray-500', type: 'hand', category: 'axes', stats: { dmg: 'D12', speed: 'Slow' }, img: 'assets/weapons/axes/battleaxe.gif' },
	'great_axe': { name: 'Great Axe', w: 2, h: 3, color: 'bg-gray-400', type: 'hand', category: 'axes', stats: { dmg: 'D12', speed: 'Normal' }, img: 'assets/weapons/axes/greataxe.gif' },
	'war_axe': { name: 'War Axe', w: 2, h: 3, color: 'bg-gray-500', type: 'hand', category: 'axes', stats: { dmg: 'D12', speed: 'Fast' }, img: 'assets/weapons/axes/waraxe.gif' },
	'giant_axe': { name: 'Giant Axe', w: 2, h: 3, color: 'bg-gray-400', type: 'hand', category: 'axes', stats: { dmg: 'D20', speed: 'Slow' }, img: 'assets/weapons/axes/giantaxe.gif' },

	// Maces & Clubs
	'club': { name: 'Club', w: 2, h: 3, color: 'bg-yellow-900', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D4', speed: 'Fast' }, img: 'assets/weapons/maces/club.gif' },
	'spiked_club': { name: 'Spiked Club', w: 2, h: 3, color: 'bg-yellow-800', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D6', speed: 'Fast' }, img: 'assets/weapons/maces/spikedclub.gif' },
	'mace': { name: 'Mace', w: 2, h: 3, color: 'bg-gray-500', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D8', speed: 'Normal' }, img: 'assets/weapons/maces/mace.gif' },
	'morning_star': { name: 'Morning Star', w: 2, h: 3, color: 'bg-gray-600', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D8', speed: 'Fast' }, img: 'assets/weapons/maces/morningstar.gif' },
	'flail': { name: 'Flail', w: 2, h: 3, color: 'bg-gray-700', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D10', speed: 'Normal' }, img: 'assets/weapons/maces/flail.gif' },
	'warhammer': { name: 'Warhammer', w: 2, h: 3, color: 'bg-gray-800', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D12', speed: 'Normal' }, img: 'assets/weapons/maces/warhammer.gif' },
	'maul': { name: 'Maul', w: 2, h: 4, color: 'bg-red-900', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D12', speed: 'Slow' }, img: 'assets/weapons/maces/maul.gif' },
	'great_maul': { name: 'Great Maul', w: 2, h: 4, color: 'bg-red-800', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D20', speed: 'Slow' }, img: 'assets/weapons/maces/greatmaul.gif' },
	'scepter': { name: 'Scepter', w: 1, h: 3, color: 'bg-yellow-400', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D6', speed: 'Fast' }, img: 'assets/weapons/scepters/scepter.gif' },
	'war_scepter': { name: 'War Scepter', w: 1, h: 3, color: 'bg-yellow-500', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D8', speed: 'Normal' }, img: 'assets/weapons/scepters/warscepter.gif' },
	'grand_scepter': { name: 'Battle Scepter', w: 1, h: 3, color: 'bg-yellow-600', type: 'hand', category: 'maces_clubs', 
		stats: { dmg: 'D10', speed: 'Fast' }, img: 'assets/weapons/scepters/grandscepter.gif' },

	// Polearms
	'scythe': { name: 'Scythe', w: 2, h: 4, color: 'bg-gray-500', type: 'hand', category: 'polearms', 
		stats: { dmg: 'D10', speed: 'Slow' }, img: 'assets/weapons/polearms/scythe.gif' },
	'poleaxe': { name: 'Poleaxe', w: 2, h: 4, color: 'bg-gray-600', type: 'hand', category: 'polearms', 
		stats: { dmg: 'D12', speed: 'Slow' }, img: 'assets/weapons/polearms/poleaxe.gif' },
	'halberd': { name: 'Halberd', w: 2, h: 4, color: 'bg-gray-700', type: 'hand', category: 'polearms', 
		stats: { dmg: 'D12', speed: 'Normal' }, img: 'assets/weapons/polearms/halberd.gif' },
	'war_scythe': { name: 'War Scythe', w: 2, h: 4, color: 'bg-gray-800', type: 'hand', category: 'polearms', 
		stats: { dmg: 'D20', speed: 'Slow' }, img: 'assets/weapons/polearms/warscythe.gif' },
	'spear': { name: 'Spear', w: 1, h: 4, color: 'bg-yellow-700', type: 'hand', category: 'polearms', 
		stats: { dmg: 'D6', speed: 'Normal' }, img: 'assets/weapons/spears/spear.gif' },
	'trident': { name: 'Trident', w: 2, h: 4, color: 'bg-blue-600', type: 'hand', category: 'polearms', 
		stats: { dmg: 'D10', speed: 'Slow' }, img: 'assets/weapons/polearms/trident.gif' },
	'brandistock': { name: 'Brandistock', w: 2, h: 4, color: 'bg-blue-700', type: 'hand', category: 'polearms', 
		stats: { dmg: 'D10', speed: 'Fast' }, img: 'assets/weapons/spears/brandistock.gif' },
	'septum': { name: 'Septum', w: 2, h: 4, color: 'bg-blue-800', type: 'hand', category: 'polearms', 
		stats: { dmg: 'D12', speed: 'Slow' }, img: 'assets/weapons/spears/septum.gif' },
	'pike': { name: 'Pike', w: 2, h: 4, color: 'bg-blue-900', type: 'hand', category: 'polearms', 
		stats: { dmg: 'D12', speed: 'Normal' }, img: 'assets/weapons/spears/pike.gif' },

	// Staves & Wands
	'short_staff': { name: 'Short Staff', w: 1, h: 3, color: 'bg-yellow-700', type: 'hand', category: 'staves_wands', 
		stats: { dmg: 'D6', speed: 'Fast' }, img: 'assets/weapons/staves/shortstaff.gif' },
	'long_staff': { name: 'Long Staff', w: 1, h: 4, color: 'bg-yellow-800', type: 'hand', category: 'staves_wands', 
		stats: { dmg: 'D8', speed: 'Fast' }, img: 'assets/weapons/staves/longstaff.gif' },
	'gnarled_staff': { name: 'Gnarled Staff', w: 1, h: 4, color: 'bg-yellow-900', type: 'hand', category: 'staves_wands', 
		stats: { dmg: 'D10', speed: 'Normal' }, img: 'assets/weapons/staves/gnarledstaff.gif' },
	'battle_staff': { name: 'Battle Staff', w: 1, h: 4, color: 'bg-red-800', type: 'hand', category: 'staves_wands', 
		stats: { dmg: 'D10', speed: 'Fast' }, img: 'assets/weapons/staves/battlestaff.gif' },
	'war_staff': { name: 'War Staff', w: 1, h: 4, color: 'bg-red-900', type: 'hand', category: 'staves_wands', 
		stats: { dmg: 'D12', speed: 'Normal' }, img: 'assets/weapons/staves/warstaff.gif' },
	'wand': { name: 'Wand', w: 1, h: 2, color: 'bg-gray-300', type: 'hand', category: 'staves_wands', 
		stats: { dmg: 'D4', speed: 'Normal' }, img: 'assets/weapons/wands/wand.gif' },
	'yew_wand': { name: 'Yew Wand', w: 1, h: 2, color: 'bg-green-300', type: 'hand', category: 'staves_wands', 
		stats: { dmg: 'D4', speed: 'Fast' }, img: 'assets/weapons/wands/yewwand.gif' },
	'bone_wand': { name: 'Bone Wand', w: 1, h: 2, color: 'bg-gray-200', type: 'hand', category: 'staves_wands', 
		stats: { dmg: 'D6', speed: 'Normal' }, img: 'assets/weapons/wands/bonewand.gif' },
	'grim_wand': { name: 'Grim Wand', w: 1, h: 2, color: 'bg-gray-400', type: 'hand', category: 'staves_wands', 
		stats: { dmg: 'D6', speed: 'Fast' }, img: 'assets/weapons/wands/grimwand.gif' },
	//TODO: Orbs

	// Potions
	'minor_healing': { name: 'Minor Health Potion', w: 1, h: 1, color: 'bg-red-100', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals D4 HP' }, img: 'assets/items/potions/minorhealing.gif' },
	'light_healing': { name: 'Light Health Potion', w: 1, h: 1, color: 'bg-red-300', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals D6 HP' }, img: 'assets/items/potions/lighthealing.gif' },
	'healing': { name: 'Health Potion', w: 1, h: 1, color: 'bg-red-500', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals D8 HP' }, img: 'assets/items/potions/healing.gif' },
	'greater_healing': { name: 'Greater Health Potion', w: 1, h: 1, color: 'bg-red-700', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals D10 HP' }, img: 'assets/items/potions/greaterhealing.gif' },
	'super_healing': { name: 'Super Health Potion', w: 1, h: 1, color: 'bg-red-900', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals D12 HP' }, img: 'assets/items/potions/superhealing.gif' },
	'minor_mana': { name: 'Minor Mana Potion', w: 1, h: 1, color: 'bg-blue-100', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals D4 HP' }, img: 'assets/items/potions/minormana.gif' },
	'light_mana': { name: 'Light Mana Potion', w: 1, h: 1, color: 'bg-blue-300', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals D6 HP' }, img: 'assets/items/potions/lightmana.gif' },
	'mana': { name: 'Mana Potion', w: 1, h: 1, color: 'bg-blue-500', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals D8 HP' }, img: 'assets/items/potions/mana.gif' },
	'greater_mana': { name: 'Greater Mana Potion', w: 1, h: 1, color: 'bg-blue-700', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals D10 HP' }, img: 'assets/items/potions/greatermana.gif' },
	'super_mana': { name: 'Super Mana Potion', w: 1, h: 1, color: 'bg-blue-900', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals D12 HP' }, img: 'assets/items/potions/supermana.gif' },
	'rejuv': { name: 'Rejuvenation Potion', w: 1, h: 1, color: 'bg-purple-300', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals 1/2 HP & Mana' }, img: 'assets/items/potions/rejuv.gif' },
	'full_rejuv': { name: 'Full Rejuvenation Potion', w: 1, h: 1, color: 'bg-purple-600', type: 'consumable', category: 'potions', 
		stats: { effect: 'Heals Full HP & Mana' }, img: 'assets/items/potions/fullrejuv.gif' },
	//TODO: add other potions

	//TODO: Scrolls

	// Gems
	'chipped_amethyst': { name: 'Chipped Amethyst', w: 1, h: 1, color: 'bg-purple-400', type: 'gem', category: 'gems', 
		stats: { weapon: '+1 Magic DMG', shield: '+1 AC', armor: '+1 STR' }, img: 'assets/items/gems/chippedamethyst.gif' },
	'flawed_amethyst': { name: 'Flawed Amethyst', w: 1, h: 1, color: 'bg-purple-500', type: 'gem', category: 'gems', 
		stats: { weapon: '+2 Magic DMG', shield: '+2 AC', armor: '+2 STR' }, img: 'assets/items/gems/flawedamethyst.gif' },
	'amethyst': { name: 'Amethyst', w: 1, h: 1, color: 'bg-purple-600', type: 'gem', category: 'gems', 
		stats: { weapon: '+3 Magic DMG', shield: '+3 AC', armor: '+3 STR' }, img: 'assets/items/gems/amethyst.gif' },
	'flawless_amethyst': { name: 'Flawless Amethyst', w: 1, h: 1, color: 'bg-purple-700', type: 'gem', category: 'gems', 
		stats: { weapon: '+4 Magic DMG', shield: '+4 AC', armor: '+4 STR' }, img: 'assets/items/gems/flawlessamethyst.gif' },
	'perfect_amethyst': { name: 'Perfect Amethyst', w: 1, h: 1, color: 'bg-purple-800', type: 'gem', category: 'gems', 
		stats: { weapon: '+5 Magic DMG', shield: '+5 AC', armor: '+5 STR' }, img: 'assets/items/gems/perfectamethyst.gif' },
	'chipped_diamond': { name: 'Chipped Diamond', w: 1, h: 1, color: 'bg-gray-100', type: 'gem', category: 'gems', 
		stats: { weapon: '+1 Physical DMG vs Undead', shield: '+1 Resist All', armor: '+1 Physical DMG' }, img: 'assets/items/gems/chippeddiamond.gif' },
	'flawed_diamond': { name: 'Flawed Diamond', w: 1, h: 1, color: 'bg-gray-200', type: 'gem', category: 'gems', 
		stats: { weapon: '+2 Physical DMG vs Undead', shield: '+2 Resist All', armor: '+2 Physical DMG' }, img: 'assets/items/gems/flaweddiamond.gif' },
	'diamond': { name: 'Diamond', w: 1, h: 1, color: 'bg-gray-300', type: 'gem', category: 'gems', 
		stats: { weapon: '+3 Physical DMG vs Undead', shield: '+3 Resist All', armor: '+3 Physical DMG' }, img: 'assets/items/gems/diamond.gif' },
	'flawless_diamond': { name: 'Flawless Diamond', w: 1, h: 1, color: 'bg-gray-400', type: 'gem', category: 'gems', 
		stats: { weapon: '+4 Physical DMG vs Undead', shield: '+4 Resist All', armor: '+4 Physical DMG' }, img: 'assets/items/gems/flawlessdiamond.gif' },
	'perfect_diamond': { name: 'Perfect Diamond', w: 1, h: 1, color: 'bg-white', type: 'gem', category: 'gems', 
		stats: { weapon: '+5 Physical DMG vs Undead', shield: '+5 Resist All', armor: '+5 Physical DMG' }, img: 'assets/items/gems/perfectdiamond.gif' },
	'chipped_emerald': { name: 'Chipped Emerald', w: 1, h: 1, color: 'bg-green-400', type: 'gem', category: 'gems', 
		stats: { weapon: '+1 Poison DMG', shield: '+1 Poison Resist', armor: '+1 DEX' }, img: 'assets/items/gems/chippedemerald.gif' },
	'flawed_emerald': { name: 'Flawed Emerald', w: 1, h: 1, color: 'bg-green-500', type: 'gem', category: 'gems', 
		stats: { weapon: '+2 Poison DMG', shield: '+2 Poison Resist', armor: '+2 DEX' }, img: 'assets/items/gems/flawedemerald.gif' },
	'emerald': { name: 'Emerald', w: 1, h: 1, color: 'bg-green-600', type: 'gem', category: 'gems', 
		stats: { weapon: '+3 Poison DMG', shield: '+3 Poison Resist', armor: '+3 DEX' }, img: 'assets/items/gems/emerald.gif' },
	'flawless_emerald': { name: 'Flawless Emerald', w: 1, h: 1, color: 'bg-green-700', type: 'gem', category: 'gems', 
		stats: { weapon: '+4 Poison DMG', shield: '+4 Poison Resist', armor: '+4 DEX' }, img: 'assets/items/gems/flawlessemerald.gif' },
	'perfect_emerald': { name: 'Perfect Emerald', w: 1, h: 1, color: 'bg-green-800', type: 'gem', category: 'gems', 
		stats: { weapon: '+5 Poison DMG', shield: '+5 Poison Resist', armor: '+5 DEX' }, img: 'assets/items/gems/perfectemerald.gif' },
	'chipped_ruby': { name: 'Chipped Ruby', w: 1, h: 1, color: 'bg-red-400', type: 'gem', category: 'gems', 
		stats: { weapon: '+1 Fire DMG', shield: '+1 Fire Resist', armor: '+5 Max Life' }, img: 'assets/items/gems/chippedruby.gif' },
	'flawed_ruby': { name: 'Flawed Ruby', w: 1, h: 1, color: 'bg-red-500', type: 'gem', category: 'gems', 
		stats: { weapon: '+2 Fire DMG', shield: '+2 Fire Resist', armor: '+10 Max Life' }, img: 'assets/items/gems/flawedruby.gif' },
	'ruby': { name: 'Ruby', w: 1, h: 1, color: 'bg-red-600', type: 'gem', category: 'gems', 
		stats: { weapon: '+3 Fire DMG', shield: '+3 Fire Resist', armor: '+15 Max Life' }, img: 'assets/items/gems/ruby.gif' },
	'flawless_ruby': { name: 'Flawless Ruby', w: 1, h: 1, color: 'bg-red-700', type: 'gem', category: 'gems', 
		stats: { weapon: '+4 Fire DMG', shield: '+4 Fire Resist', armor: '+20 Max Life' }, img: 'assets/items/gems/flawlessruby.gif' },
	'perfect_ruby': { name: 'Perfect Ruby', w: 1, h: 1, color: 'bg-red-800', type: 'gem', category: 'gems', 
		stats: { weapon: '+5 Fire DMG', shield: '+5 Fire Resist', armor: '+25 Max Life' }, img: 'assets/items/gems/perfectruby.gif' },
	'chipped_saphire': { name: 'Chipped Saphire', w: 1, h: 1, color: 'bg-blue-400', type: 'gem', category: 'gems', 
		stats: { weapon: '+1 Cold DMG', shield: '+1 Cold Resist', armor: '+5 Max Mana' }, img: 'assets/items/gems/chippedsaphire.gif' },
	'flawed_saphire': { name: 'Flawed Saphire', w: 1, h: 1, color: 'bg-blue-500', type: 'gem', category: 'gems', 
		stats: { weapon: '+2 Cold DMG', shield: '+2 Cold Resist', armor: '+10 Max Mana' }, img: 'assets/items/gems/flawedsaphire.gif' },
	'saphire': { name: 'Saphire', w: 1, h: 1, color: 'bg-blue-600', type: 'gem', category: 'gems', 
		stats: { weapon: '+3 Cold DMG', shield: '+3 Cold Resist', armor: '+15 Max Mana' }, img: 'assets/items/gems/saphire.gif' },
	'flawless_saphire': { name: 'Flawless Saphire', w: 1, h: 1, color: 'bg-blue-700', type: 'gem', category: 'gems', 
		stats: { weapon: '+4 Cold DMG', shield: '+4 Cold Resist', armor: '+20 Max Mana' }, img: 'assets/items/gems/flawlesssaphire.gif' },
	'perfect_saphire': { name: 'Perfect Saphire', w: 1, h: 1, color: 'bg-blue-800', type: 'gem', category: 'gems', 
		stats: { weapon: '+5 Cold DMG', shield: '+5 Cold Resist', armor: '+25 Max Mana' }, img: 'assets/items/gems/perfectsaphire.gif' },
	'chipped_skull': { name: 'Chipped Skull', w: 1, h: 1, color: 'bg-gray-300', type: 'gem', category: 'gems', 
		stats: { weapon: '+1 Life/Mana Steal', shield: '+1 Thorns', armor: '+1 Replenish HP & Mana' }, img: 'assets/items/gems/chippedskull.gif' },
	'flawed_skull': { name: 'Flawed Skull', w: 1, h: 1, color: 'bg-gray-400', type: 'gem', category: 'gems', 
		stats: { weapon: '+2 Life/Mana Steal', shield: '+2 Thorns', armor: '+2 Replenish HP & Mana' }, img: 'assets/items/gems/flawedskull.gif' },
	'skull': { name: 'Skull', w: 1, h: 1, color: 'bg-gray-500', type: 'gem', category: 'gems', 
		stats: { weapon: '+3 Life/Mana Steal', shield: '+3 Thorns', armor: '+3 Replenish HP & Mana' }, img: 'assets/items/gems/skull.gif' },
	'flawless_skull': { name: 'Flawless Skull', w: 1, h: 1, color: 'bg-gray-600', type: 'gem', category: 'gems', 
		stats: { weapon: '+4 Life/Mana Steal', shield: '+4 Thorns', armor: '+4 Replenish HP & Mana' }, img: 'assets/items/gems/flawlessskull.gif' },
	'perfect_skull': { name: 'Perfect Skull', w: 1, h: 1, color: 'bg-gray-700', type: 'gem', category: 'gems', 
		stats: { weapon: '+5 Life/Mana Steal', shield: '+5 Thorns', armor: '+5 Replenish HP & Mana' }, img: 'assets/items/gems/perfectskull.gif' },
	'chipped_topaz': { name: 'Chipped Topaz', w: 1, h: 1, color: 'bg-yellow-400', type: 'gem', category: 'gems', 
		stats: { weapon: '+1 Lightning DMG', shield: '+1 Lightning Resist', armor: '+1 Magic Find' }, img: 'assets/items/gems/chippedtopaz.gif' },
	'flawed_topaz': { name: 'Flawed Topaz', w: 1, h: 1, color: 'bg-yellow-500', type: 'gem', category: 'gems', 
		stats: { weapon: '+2 Lightning DMG', shield: '+2 Lightning Resist', armor: '+2 Magic Find' }, img: 'assets/items/gems/flawedtopaz.gif' },
	'topaz': { name: 'Topaz', w: 1, h: 1, color: 'bg-yellow-600', type: 'gem', category: 'gems', 
		stats: { weapon: '+3 Lightning DMG', shield: '+3 Lightning Resist', armor: '+3 Magic Find' }, img: 'assets/items/gems/topaz.gif' },
	'flawless_topaz': { name: 'Flawless Topaz', w: 1, h: 1, color: 'bg-yellow-700', type: 'gem', category: 'gems', 
		stats: { weapon: '+4 Lightning DMG', shield: '+4 Lightning Resist', armor: '+4 Magic Find' }, img: 'assets/items/gems/flawlesstopaz.gif' },
	'perfect_topaz': { name: 'Perfect Topaz', w: 1, h: 1, color: 'bg-yellow-800', type: 'gem', category: 'gems', 
		stats: { weapon: '+5 Lightning DMG', shield: '+5 Lightning Resist', armor: '+5 Magic Find' }, img: 'assets/items/gems/perfecttopaz.gif' },
	
	//Boots
	'leather_boots': { name: 'Boots', w: 2, h: 2, color: 'bg-yellow-900', type: 'feet', category: 'boots', 
		stats: { ac: 1, weight: 'Light' }, img: 'assets/armor/boots/leatherboots.gif' },
	'heavy_boots': { name: 'Heavy Boots', w: 2, h: 2, color: 'bg-yellow-800', type: 'feet', category: 'boots', 
		stats: { ac: 1, weight: 'Medium' }, img: 'assets/armor/boots/heavyboots.gif' },
	'chain_boots': { name: 'Chain Boots', w: 2, h: 2, color: 'bg-gray-500', type: 'feet', category: 'boots', 
		stats: { ac: 2, weight: 'Medium' }, img: 'assets/armor/boots/chainboots.gif' },
	'light_plate_boots': { name: 'Light Plate Boots', w: 2, h: 2, color: 'bg-gray-400', type: 'feet', category: 'boots', 
		stats: { ac: 2, weight: 'Heavy' }, img: 'assets/armor/boots/lightplateboots.gif' },
	'plate_boots': { name: 'Plate Boots', w: 2, h: 2, color: 'bg-gray-300', type: 'feet', category: 'boots', 
		stats: { ac: 3, weight: 'Heavy' }, img: 'assets/armor/boots/plateboots.gif' },
	
	//Gloves
	'leather_gloves': { name: 'Leather Gloves', w: 2, h: 2, color: 'bg-yellow-800', type: 'hands', category: 'gloves', 
		stats: { ac: 1, weight: 'Light' }, img: 'assets/armor/gloves/leathergloves.gif' },
	'chain_gloves': { name: 'Chain Gloves', w: 2, h: 2, color: 'bg-gray-500', type: 'hands', category: 'gloves', 
		stats: { ac: 2, weight: 'Light' }, img: 'assets/armor/gloves/chaingloves.gif' },
	'heavy_gloves': { name: 'Heavy Gloves', w: 2, h: 2, color: 'bg-yellow-900', type: 'hands', category: 'gloves', 
		stats: { ac: 2, weight: 'Medium' }, img: 'assets/armor/gloves/heavygloves.gif' },
	'light_gauntlets': { name: 'Light Gauntlets', w: 2, h: 2, color: 'bg-gray-400', type: 'hands', category: 'gloves', 
		stats: { ac: 3, weight: 'Medium' }, img: 'assets/armor/gloves/lightgauntlets.gif' },
	'gauntlets': { name: 'Gauntlets', w: 2, h: 2, color: 'bg-gray-600', type: 'hands', category: 'gloves', 
		stats: { ac: 4, weight: 'Heavy' }, img: 'assets/armor/gloves/gauntlets.gif' },
	
	//Belts
	'sash': { name: 'Sash', w: 2, h: 1, color: 'bg-amber-200', type: 'waist', category: 'belts', 
		stats: { ac: 1, cap: 4 }, img: 'assets/armor/belts/sash.gif' },
	'light_belt': { name: 'Light Belt', w: 2, h: 1, color: 'bg-slate-300', type: 'waist', category: 'belts', 
		stats: { ac: 1, cap: 8 }, img: 'assets/armor/belts/lightbelt.gif' },
	'belt': { name: 'Belt', w: 2, h: 1, color: 'bg-amber-600', type: 'waist', category: 'belts', 
		stats: { ac: 2, cap: 8 }, img: 'assets/armor/belts/belt.gif' },
	'heavy_belt': { name: 'Heavy Belt', w: 2, h: 1, color: 'bg-amber-800', type: 'waist', category: 'belts', 
		stats: { ac: 2, cap: 12 }, img: 'assets/armor/belts/heavybelt.gif' },
	'plate_belt': { name: 'Plate Belt', w: 2, h: 1, color: 'bg-slate-500', type: 'waist', category: 'belts', 
		stats: { ac: 3, cap: 16 }, img: 'assets/armor/belts/platebelt.gif' },
	
	// Jewelry
	'ring1': { name: 'Gold Ring', w: 1, h: 1, color: 'bg-amber-400', type: 'finger', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/ring1.gif' },
	'ring2': { name: 'Silver Ring', w: 1, h: 1, color: 'bg-slate-300', type: 'finger', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/ring2.gif' },
	'ring3': { name: 'Platinum Ring', w: 1, h: 1, color: 'bg-neutral-500', type: 'finger', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/ring3.gif' },
	'ring4': { name: 'Platinum Ring', w: 1, h: 1, color: 'bg-neutral-500', type: 'finger', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/ring4.gif' },
	'ring5': { name: 'Platinum Ring', w: 1, h: 1, color: 'bg-neutral-500', type: 'finger', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/ring5.gif' },
	'amulet_a': { name: 'Amulet', w: 1, h: 1, color: 'bg-red-500', type: 'neck', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/amu1.gif' },
	'amulet_b': { name: 'Amulet', w: 1, h: 1, color: 'bg-red-500', type: 'neck', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/amu2.gif' },
	'amulet_c': { name: 'Amulet', w: 1, h: 1, color: 'bg-red-500', type: 'neck', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/amu3.gif' },
	'jewel_a': { name: 'Jewel', w: 1, h: 1, color: 'bg-cyan-400', type: 'socket', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/jewel01.gif' },
	'jewel_b': { name: 'Jewel', w: 1, h: 1, color: 'bg-violet-500', type: 'socket', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/jewel02.gif' },
	'jewel_c': { name: 'Jewel', w: 1, h: 1, color: 'bg-green-500', type: 'socket', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/jewel03.gif' },
	'jewel_d': { name: 'Jewel', w: 1, h: 1, color: 'bg-green-500', type: 'socket', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/jewel04.gif' },
	'jewel_e': { name: 'Jewel', w: 1, h: 1, color: 'bg-green-500', type: 'socket', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/jewel05.gif' },
	'jewel_4': { name: 'Jewel', w: 1, h: 1, color: 'bg-green-500', type: 'socket', category: 'jewelry', 
		stats: {}, img: 'assets/items/jewelry/jewel06.gif' },
	
	// Charms
	'charm_small_a': { name: 'Charm', w: 1, h: 1, color: 'bg-orange-200', type: 'charm', category: 'charms', 
		stats: {}, img: 'assets/items/charms/smallcharm01.gif' },
	'charm_small_b': { name: 'Charm', w: 1, h: 1, color: 'bg-orange-300', type: 'charm', category: 'charms', 
		stats: {}, img: 'assets/items/charms/smallcharm02.gif' },
	'charm_small_c': { name: 'Charm', w: 1, h: 1, color: 'bg-orange-400', type: 'charm', category: 'charms', 
		stats: {}, img: 'assets/items/charms/smallcharm03.gif' },
	'charm_medium_a': { name: 'Charm', w: 1, h: 2, color: 'bg-amber-200', type: 'charm', category: 'charms', 
		stats: {}, img: 'assets/items/charms/mediumcharm01.gif' },
	'charm_medium_b': { name: 'Charm', w: 1, h: 2, color: 'bg-amber-300', type: 'charm', category: 'charms', 
		stats: {}, img: 'assets/items/charms/mediumcharm02.gif' },
	'charm_medium_c': { name: 'Charm', w: 1, h: 2, color: 'bg-amber-400', type: 'charm', category: 'charms', 
		stats: {}, img: 'assets/items/charms/mediumcharm03.gif' },
	'charm_large_a': { name: 'Charm', w: 1, h: 3, color: 'bg-yellow-200', type: 'charm', category: 'charms', 
		stats: {}, img: 'assets/items/charms/largecharm01.gif' },
	'charm_large_b': { name: 'Charm', w: 1, h: 3, color: 'bg-yellow-300', type: 'charm', category: 'charms', 
		stats: {}, img: 'assets/items/charms/largecharm02.gif' },
	'charm_large_c': { name: 'Charm', w: 1, h: 3, color: 'bg-yellow-400', type: 'charm', category: 'charms', 
		stats: {}, img: 'assets/items/charms/largecharm03.gif' },
}