// --- DATA & CONSTANTS ---
const characterData = { 
	amazon: { stats: { str: 14, dex: 14, con: 16, int: 10, wis: 14, cha: 16 }, life: { current: 22, max: 22, regen: 3 }, mana: { current: 16, max: 16, regen: 1 }, ac: 3, moveRate: 20 }, 
	paladin: { stats: { str: 14, dex: 14, con: 16, int: 10, wis: 14, cha: 16 }, life: { current: 22, max: 22, regen: 3 }, mana: { current: 16, max: 16, regen: 1 }, ac: 2, moveRate: 20 }, 
	barbarian: { stats: { str: 18, dex: 13, con: 17, int: 8, wis: 10, cha: 11 }, life: { current: 25, max: 25, regen: 3 }, mana: { current: 8, max: 8, regen: 1 }, ac: 1, moveRate: 30 }, 
	sorceress: { stats: { str: 8, dex: 12, con: 10, int: 18, wis: 16, cha: 14 }, life: { current: 15, max: 15, regen: 1 }, mana: { current: 30, max: 30, regen: 4 }, ac: 1, moveRate: 30 } };
	
const itemDatabase = {
	// Body Armor
	'quilted_armor': { name: 'Quilted Armor', w: 2, h: 3, color: 'bg-gray-800', type: 'body', category: 'armor', stats: { ac: 1, weight: 'Light' }, img: 'assets/armor/quiltedarmor.gif' },
	'leather_armor': { name: 'Leather Armor', w: 2, h: 3, color: 'bg-yellow-900', type: 'body', category: 'armor', stats: { ac: 2, weight: 'Light' } },
	'hard_leather_armor': { name: 'Hard Leather Armor', w: 2, h: 3, color: 'bg-yellow-800', type: 'body', category: 'armor', stats: { ac: 3, weight: 'Light' } },
	'studded_armor': { name: 'Studded Armor', w: 2, h: 3, color: 'bg-gray-700', type: 'body', category: 'armor', stats: { ac: 4, weight: 'Medium' } },
	'ring_mail': { name: 'Ring Mail', w: 2, h: 3, color: 'bg-gray-600', type: 'body', category: 'armor', stats: { ac: 4, weight: 'Light' } },
	'scale_mail': { name: 'Scale Mail', w: 2, h: 3, color: 'bg-gray-500', type: 'body', category: 'armor', stats: { ac: 5, weight: 'Heavy' } },
	'chain_mail': { name: 'Chain Mail', w: 2, h: 3, color: 'bg-gray-600', type: 'body', category: 'armor', stats: { ac: 5, weight: 'Medium' } },
	'breast_plate': { name: 'Breast Plate', w: 2, h: 3, color: 'bg-gray-400', type: 'body', category: 'armor', stats: { ac: 5, weight: 'Light' } },
	'splint_mail': { name: 'Splint Mail', w: 2, h: 3, color: 'bg-gray-500', type: 'body', category: 'armor', stats: { ac: 6, weight: 'Medium' } },
	'plate_mail': { name: 'Plate Mail', w: 2, h: 3, color: 'bg-gray-400', type: 'body', category: 'armor', stats: { ac: 7, weight: 'Heavy' } },
	'field_plate': { name: 'Field Plate', w: 2, h: 3, color: 'bg-gray-300', type: 'body', category: 'armor', stats: { ac: 7, weight: 'Medium' } },
	'gothic_plate': { name: 'Gothic Plate', w: 2, h: 3, color: 'bg-gray-200', type: 'body', category: 'armor', stats: { ac: 8, weight: 'Medium' } },
	'light_plate': { name: 'Light Plate', w: 2, h: 3, color: 'bg-gray-100', type: 'body', category: 'armor', stats: { ac: 8, weight: 'Light' } },
	'full_plate_mail': { name: 'Full Plate Mail', w: 2, h: 3, color: 'bg-white', type: 'body', category: 'armor', stats: { ac: 9, weight: 'Heavy' } },
	'ancient_armor': { name: 'Ancient Armor', w: 2, h: 3, color: 'bg-yellow-200', type: 'body', category: 'armor', stats: { ac: 10, weight: 'Medium' } },

	// Helms
	'cap': { name: 'Cap', w: 2, h: 2, color: 'bg-yellow-800', type: 'head', category: 'helms', stats: { ac: 1 } },
	'skull_cap': { name: 'Skull Cap', w: 2, h: 2, color: 'bg-gray-300', type: 'head', category: 'helms', stats: { ac: 2 } },
	'helm': { name: 'Helm', w: 2, h: 2, color: 'bg-gray-700', type: 'head', category: 'helms', stats: { ac: 3 } },
	'mask': { name: 'Mask', w: 2, h: 2, color: 'bg-yellow-600', type: 'head', category: 'helms', stats: { ac: 3 } },
	'full_helm': { name: 'Full Helm', w: 2, h: 2, color: 'bg-gray-600', type: 'head', category: 'helms', stats: { ac: 4 } },
	'bone_helm': { name: 'Bone Helm', w: 2, h: 2, color: 'bg-gray-200', type: 'head', category: 'helms', stats: { ac: 5 } },
	'great_helm': { name: 'Great Helm', w: 2, h: 2, color: 'bg-gray-500', type: 'head', category: 'helms', stats: { ac: 5 } },
	'crown': { name: 'Crown', w: 2, h: 2, color: 'bg-yellow-500', type: 'head', category: 'helms', stats: { ac: 5 } },

	// Shields
	'buckler': { name: 'Buckler', w: 2, h: 2, color: 'bg-yellow-900', type: 'offhand', category: 'shields', stats: { ac: 1, weight: 'Light' } },
	'small_shield': { name: 'Small Shield', w: 2, h: 2, color: 'bg-yellow-800', type: 'offhand', category: 'shields', stats: { ac: 2, weight: 'Light' } },
	'large_shield': { name: 'Large Shield', w: 2, h: 3, color: 'bg-yellow-700', type: 'offhand', category: 'shields', stats: { ac: 3, weight: 'Light' } },
	'spiked_shield': { name: 'Spiked Shield', w: 2, h: 2, color: 'bg-gray-500', type: 'offhand', category: 'shields', stats: { ac: 3, weight: 'Light' } },
	'kite_shield': { name: 'Kite Shield', w: 2, h: 3, color: 'bg-blue-300', type: 'offhand', category: 'shields', stats: { ac: 4, weight: 'Light' } },
	'bone_shield': { name: 'Bone Shield', w: 2, h: 3, color: 'bg-gray-200', type: 'offhand', category: 'shields', stats: { ac: 5, weight: 'Light' } },
	'tower_shield': { name: 'Tower Shield', w: 2, h: 3, color: 'bg-gray-500', type: 'offhand', category: 'shields', stats: { ac: 6, weight: 'Heavy' } },
	'gothic_shield': { name: 'Gothic Shield', w: 2, h: 3, color: 'bg-red-800', type: 'offhand', category: 'shields', stats: { ac: 6, weight: 'Medium' } },

	// Swords
	'shortsword': { name: 'Shortsword', w: 1, h: 3, color: 'bg-blue-200', type: 'weapon', category: 'swords', stats: { dmg: 'D4', speed: 'Fast' } },
	'scimitar': { name: 'Scimitar', w: 1, h: 3, color: 'bg-blue-300', type: 'weapon', category: 'swords', stats: { dmg: 'D4', speed: 'Very Fast' } },
	'saber': { name: 'Saber', w: 1, h: 3, color: 'bg-blue-400', type: 'weapon', category: 'swords', stats: { dmg: 'D6', speed: 'Fast' } },
	'crystal_sword': { name: 'Crystal Sword', w: 1, h: 3, color: 'bg-blue-100', type: 'weapon', category: 'swords', stats: { dmg: 'D8', speed: 'Fast' } },
	'falchion': { name: 'Falchion', w: 1, h: 3, color: 'bg-blue-500', type: 'weapon', category: 'swords', stats: { dmg: 'D10', speed: 'Slow' } },
	'broadsword': { name: 'Broadsword', w: 2, h: 3, color: 'bg-blue-600', type: 'weapon', category: 'swords', stats: { dmg: 'D10', speed: 'Fast' } },
	'longsword': { name: 'Longsword', w: 2, h: 3, color: 'bg-blue-700', type: 'weapon', category: 'swords', stats: { dmg: 'D12', speed: 'Fast' } },
	'two_handed_sword': { name: 'Two Handed Sword', w: 2, h: 4, color: 'bg-blue-800', type: 'weapon', category: 'swords', stats: { dmg: 'D4/D8', speed: 'Fast' } },
	'claymore': { name: 'Claymore', w: 2, h: 4, color: 'bg-blue-900', type: 'weapon', category: 'swords', stats: { dmg: 'D6/D10', speed: 'Normal' } },
	'giant_sword': { name: 'Giant Sword', w: 2, h: 4, color: 'bg-blue-800', type: 'weapon', category: 'swords', stats: { dmg: 'D6/D10', speed: 'Fast' } },
	'bastard_sword': { name: 'Bastard Sword', w: 2, h: 4, color: 'bg-blue-700', type: 'weapon', category: 'swords', stats: { dmg: 'D8/D12', speed: 'Normal' } },
	'flamberge': { name: 'Flamberge', w: 2, h: 4, color: 'bg-blue-600', type: 'weapon', category: 'swords', stats: { dmg: 'D8/D12', speed: 'Fast' } },
	'war_sword': { name: 'War Sword', w: 2, h: 4, color: 'bg-blue-500', type: 'weapon', category: 'swords', stats: { dmg: 'D10/D12', speed: 'Fast' } },
	'great_sword': { name: 'Great Sword', w: 2, h: 4, color: 'bg-blue-400', type: 'weapon', category: 'swords', stats: { dmg: 'D10/D20', speed: 'Normal' } },

	// Axes
	'hand_axe': { name: 'Hand Axe', w: 2, h: 3, color: 'bg-gray-400', type: 'weapon', category: 'axes', stats: { dmg: 'D4', speed: 'Fast' } },
	'large_axe': { name: 'Large Axe', w: 2, h: 3, color: 'bg-gray-500', type: 'weapon', category: 'axes', stats: { dmg: 'D6', speed: 'Slow' } },
	'axe': { name: 'Axe', w: 2, h: 3, color: 'bg-gray-400', type: 'weapon', category: 'axes', stats: { dmg: 'D6', speed: 'Normal' } },
	'broad_axe': { name: 'Broad Axe', w: 2, h: 3, color: 'bg-gray-500', type: 'weapon', category: 'axes', stats: { dmg: 'D8', speed: 'Normal' } },
	'double_axe': { name: 'Double Axe', w: 2, h: 3, color: 'bg-gray-400', type: 'weapon', category: 'axes', stats: { dmg: 'D10', speed: 'Normal' } },
	'battle_axe': { name: 'Battle Axe', w: 2, h: 3, color: 'bg-gray-500', type: 'weapon', category: 'axes', stats: { dmg: 'D12', speed: 'Slow' } },
	'great_axe': { name: 'Great Axe', w: 2, h: 3, color: 'bg-gray-400', type: 'weapon', category: 'axes', stats: { dmg: 'D12', speed: 'Normal' } },
	'war_axe': { name: 'War Axe', w: 2, h: 3, color: 'bg-gray-500', type: 'weapon', category: 'axes', stats: { dmg: 'D12', speed: 'Fast' } },
	'giant_axe': { name: 'Giant Axe', w: 2, h: 3, color: 'bg-gray-400', type: 'weapon', category: 'axes', stats: { dmg: 'D20', speed: 'Slow' } },

	// Maces & Clubs
	'club': { name: 'Club', w: 2, h: 3, color: 'bg-yellow-900', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D4', speed: 'Fast' } },
	'spiked_club': { name: 'Spiked Club', w: 2, h: 3, color: 'bg-yellow-800', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D6', speed: 'Fast' } },
	'mace': { name: 'Mace', w: 2, h: 3, color: 'bg-gray-500', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D8', speed: 'Normal' } },
	'morning_star': { name: 'Morning Star', w: 2, h: 3, color: 'bg-gray-600', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D8', speed: 'Fast' } },
	'flail': { name: 'Flail', w: 2, h: 3, color: 'bg-gray-700', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D10', speed: 'Normal' } },
	'warhammer': { name: 'Warhammer', w: 2, h: 3, color: 'bg-gray-800', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D12', speed: 'Normal' } },
	'maul': { name: 'Maul', w: 2, h: 4, color: 'bg-red-900', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D12', speed: 'Slow' } },
	'great_maul': { name: 'Great Maul', w: 2, h: 4, color: 'bg-red-800', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D20', speed: 'Slow' } },
	'scepter': { name: 'Scepter', w: 1, h: 3, color: 'bg-yellow-400', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D6', speed: 'Fast' } },
	'war_scepter': { name: 'War Scepter', w: 1, h: 3, color: 'bg-yellow-500', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D8', speed: 'Normal' } },
	'battle_scepter': { name: 'Battle Scepter', w: 1, h: 3, color: 'bg-yellow-600', type: 'weapon', category: 'maces_clubs', stats: { dmg: 'D10', speed: 'Fast' } },

	// Polearms
	'scythe': { name: 'Scythe', w: 2, h: 4, color: 'bg-gray-500', type: 'weapon', category: 'polearms', stats: { dmg: 'D10', speed: 'Slow' } },
	'poleaxe': { name: 'Poleaxe', w: 2, h: 4, color: 'bg-gray-600', type: 'weapon', category: 'polearms', stats: { dmg: 'D12', speed: 'Slow' } },
	'halberd': { name: 'Halberd', w: 2, h: 4, color: 'bg-gray-700', type: 'weapon', category: 'polearms', stats: { dmg: 'D12', speed: 'Normal' } },
	'war_scythe': { name: 'War Scythe', w: 2, h: 4, color: 'bg-gray-800', type: 'weapon', category: 'polearms', stats: { dmg: 'D20', speed: 'Slow' } },
	'spear': { name: 'Spear', w: 1, h: 4, color: 'bg-yellow-700', type: 'weapon', category: 'polearms', stats: { dmg: 'D6', speed: 'Normal' } },
	'trident': { name: 'Trident', w: 2, h: 4, color: 'bg-blue-600', type: 'weapon', category: 'polearms', stats: { dmg: 'D10', speed: 'Slow' } },
	'brandistock': { name: 'Brandistock', w: 2, h: 4, color: 'bg-blue-700', type: 'weapon', category: 'polearms', stats: { dmg: 'D10', speed: 'Fast' } },
	'septum': { name: 'Septum', w: 2, h: 4, color: 'bg-blue-800', type: 'weapon', category: 'polearms', stats: { dmg: 'D12', speed: 'Slow' } },
	'pike': { name: 'Pike', w: 2, h: 4, color: 'bg-blue-900', type: 'weapon', category: 'polearms', stats: { dmg: 'D12', speed: 'Normal' } },

	// Staves & Wands
	'short_staff': { name: 'Short Staff', w: 1, h: 3, color: 'bg-yellow-700', type: 'weapon', category: 'staves_wands', stats: { dmg: 'D6', speed: 'Fast' } },
	'long_staff': { name: 'Long Staff', w: 1, h: 4, color: 'bg-yellow-800', type: 'weapon', category: 'staves_wands', stats: { dmg: 'D8', speed: 'Fast' } },
	'gnarled_staff': { name: 'Gnarled Staff', w: 1, h: 4, color: 'bg-yellow-900', type: 'weapon', category: 'staves_wands', stats: { dmg: 'D10', speed: 'Normal' } },
	'battle_staff': { name: 'Battle Staff', w: 1, h: 4, color: 'bg-red-800', type: 'weapon', category: 'staves_wands', stats: { dmg: 'D10', speed: 'Fast' } },
	'war_staff': { name: 'War Staff', w: 1, h: 4, color: 'bg-red-900', type: 'weapon', category: 'staves_wands', stats: { dmg: 'D12', speed: 'Normal' } },
	'wand': { name: 'Wand', w: 1, h: 2, color: 'bg-gray-300', type: 'weapon', category: 'staves_wands', stats: { dmg: 'D4', speed: 'Normal' } },
	'yew_wand': { name: 'Yew Wand', w: 1, h: 2, color: 'bg-green-300', type: 'weapon', category: 'staves_wands', stats: { dmg: 'D4', speed: 'Fast' } },
	'bone_wand': { name: 'Bone Wand', w: 1, h: 2, color: 'bg-gray-200', type: 'weapon', category: 'staves_wands', stats: { dmg: 'D6', speed: 'Normal' } },
	'grim_wand': { name: 'Grim Wand', w: 1, h: 2, color: 'bg-gray-400', type: 'weapon', category: 'staves_wands', stats: { dmg: 'D6', speed: 'Fast' } },

	// Potions
	'minor_health_potion': { name: 'Minor Health Potion', w: 1, h: 1, color: 'bg-red-100', type: 'consumable', category: 'potions', stats: { effect: 'Heals D4 HP' } },
	'light_health_potion': { name: 'Light Health Potion', w: 1, h: 1, color: 'bg-red-300', type: 'consumable', category: 'potions', stats: { effect: 'Heals D6 HP' } },
	'health_potion': { name: 'Health Potion', w: 1, h: 1, color: 'bg-red-500', type: 'consumable', category: 'potions', stats: { effect: 'Heals D8 HP' } },
	'greater_health_potion': { name: 'Greater Health Potion', w: 1, h: 1, color: 'bg-red-700', type: 'consumable', category: 'potions', stats: { effect: 'Heals D10 HP' } },
	'super_health_potion': { name: 'Super Health Potion', w: 1, h: 1, color: 'bg-red-900', type: 'consumable', category: 'potions', stats: { effect: 'Heals D12 HP' } },
	'minor_mana_potion': { name: 'Minor Mana Potion', w: 1, h: 1, color: 'bg-blue-100', type: 'consumable', category: 'potions', stats: { effect: 'Heals D4 HP' } },
	'light_mana_potion': { name: 'Light Mana Potion', w: 1, h: 1, color: 'bg-blue-300', type: 'consumable', category: 'potions', stats: { effect: 'Heals D6 HP' } },
	'mana_potion': { name: 'Mana Potion', w: 1, h: 1, color: 'bg-blue-500', type: 'consumable', category: 'potions', stats: { effect: 'Heals D8 HP' } },
	'greater_mana_potion': { name: 'Greater Mana Potion', w: 1, h: 1, color: 'bg-blue-700', type: 'consumable', category: 'potions', stats: { effect: 'Heals D10 HP' } },
	'super_mana_potion': { name: 'Super Mana Potion', w: 1, h: 1, color: 'bg-blue-900', type: 'consumable', category: 'potions', stats: { effect: 'Heals D12 HP' } },
	'rejuvenation_potion': { name: 'Rejuvenation Potion', w: 1, h: 1, color: 'bg-purple-300', type: 'consumable', category: 'potions', stats: { effect: 'Heals 1/2 HP & Mana' } },
	'full_rejuvenation_potion': { name: 'Full Rejuvenation Potion', w: 1, h: 1, color: 'bg-purple-600', type: 'consumable', category: 'potions', stats: { effect: 'Heals Full HP & Mana' } },

	// Gems
	'chipped_amethyst': { name: 'Chipped Amethyst', w: 1, h: 1, color: 'bg-purple-400', type: 'gem', category: 'gems', stats: { weapon: '+1 Magic DMG', shield: '+1 AC', armor: '+1 STR' } },
	'flawed_amethyst': { name: 'Flawed Amethyst', w: 1, h: 1, color: 'bg-purple-500', type: 'gem', category: 'gems', stats: { weapon: '+2 Magic DMG', shield: '+2 AC', armor: '+2 STR' } },
	'amethyst': { name: 'Amethyst', w: 1, h: 1, color: 'bg-purple-600', type: 'gem', category: 'gems', stats: { weapon: '+3 Magic DMG', shield: '+3 AC', armor: '+3 STR' } },
	'flawless_amethyst': { name: 'Flawless Amethyst', w: 1, h: 1, color: 'bg-purple-700', type: 'gem', category: 'gems', stats: { weapon: '+4 Magic DMG', shield: '+4 AC', armor: '+4 STR' } },
	'perfect_amethyst': { name: 'Perfect Amethyst', w: 1, h: 1, color: 'bg-purple-800', type: 'gem', category: 'gems', stats: { weapon: '+5 Magic DMG', shield: '+5 AC', armor: '+5 STR' } },
	'chipped_diamond': { name: 'Chipped Diamond', w: 1, h: 1, color: 'bg-gray-100', type: 'gem', category: 'gems', stats: { weapon: '+1 Physical DMG vs Undead', shield: '+1 Resist All', armor: '+1 Physical DMG' } },
	'flawed_diamond': { name: 'Flawed Diamond', w: 1, h: 1, color: 'bg-gray-200', type: 'gem', category: 'gems', stats: { weapon: '+2 Physical DMG vs Undead', shield: '+2 Resist All', armor: '+2 Physical DMG' } },
	'diamond': { name: 'Diamond', w: 1, h: 1, color: 'bg-gray-300', type: 'gem', category: 'gems', stats: { weapon: '+3 Physical DMG vs Undead', shield: '+3 Resist All', armor: '+3 Physical DMG' } },
	'flawless_diamond': { name: 'Flawless Diamond', w: 1, h: 1, color: 'bg-gray-400', type: 'gem', category: 'gems', stats: { weapon: '+4 Physical DMG vs Undead', shield: '+4 Resist All', armor: '+4 Physical DMG' } },
	'perfect_diamond': { name: 'Perfect Diamond', w: 1, h: 1, color: 'bg-white', type: 'gem', category: 'gems', stats: { weapon: '+5 Physical DMG vs Undead', shield: '+5 Resist All', armor: '+5 Physical DMG' } },
	'chipped_emerald': { name: 'Chipped Emerald', w: 1, h: 1, color: 'bg-green-400', type: 'gem', category: 'gems', stats: { weapon: '+1 Poison DMG', shield: '+1 Poison Resist', armor: '+1 DEX' } },
	'flawed_emerald': { name: 'Flawed Emerald', w: 1, h: 1, color: 'bg-green-500', type: 'gem', category: 'gems', stats: { weapon: '+2 Poison DMG', shield: '+2 Poison Resist', armor: '+2 DEX' } },
	'emerald': { name: 'Emerald', w: 1, h: 1, color: 'bg-green-600', type: 'gem', category: 'gems', stats: { weapon: '+3 Poison DMG', shield: '+3 Poison Resist', armor: '+3 DEX' } },
	'flawless_emerald': { name: 'Flawless Emerald', w: 1, h: 1, color: 'bg-green-700', type: 'gem', category: 'gems', stats: { weapon: '+4 Poison DMG', shield: '+4 Poison Resist', armor: '+4 DEX' } },
	'perfect_emerald': { name: 'Perfect Emerald', w: 1, h: 1, color: 'bg-green-800', type: 'gem', category: 'gems', stats: { weapon: '+5 Poison DMG', shield: '+5 Poison Resist', armor: '+5 DEX' } },
	'chipped_ruby': { name: 'Chipped Ruby', w: 1, h: 1, color: 'bg-red-400', type: 'gem', category: 'gems', stats: { weapon: '+1 Fire DMG', shield: '+1 Fire Resist', armor: '+5 Max Life' } },
	'flawed_ruby': { name: 'Flawed Ruby', w: 1, h: 1, color: 'bg-red-500', type: 'gem', category: 'gems', stats: { weapon: '+2 Fire DMG', shield: '+2 Fire Resist', armor: '+10 Max Life' } },
	'ruby': { name: 'Ruby', w: 1, h: 1, color: 'bg-red-600', type: 'gem', category: 'gems', stats: { weapon: '+3 Fire DMG', shield: '+3 Fire Resist', armor: '+15 Max Life' } },
	'flawless_ruby': { name: 'Flawless Ruby', w: 1, h: 1, color: 'bg-red-700', type: 'gem', category: 'gems', stats: { weapon: '+4 Fire DMG', shield: '+4 Fire Resist', armor: '+20 Max Life' } },
	'perfect_ruby': { name: 'Perfect Ruby', w: 1, h: 1, color: 'bg-red-800', type: 'gem', category: 'gems', stats: { weapon: '+5 Fire DMG', shield: '+5 Fire Resist', armor: '+25 Max Life' } },
	'chipped_sapphire': { name: 'Chipped Sapphire', w: 1, h: 1, color: 'bg-blue-400', type: 'gem', category: 'gems', stats: { weapon: '+1 Cold DMG', shield: '+1 Cold Resist', armor: '+5 Max Mana' } },
	'flawed_sapphire': { name: 'Flawed Sapphire', w: 1, h: 1, color: 'bg-blue-500', type: 'gem', category: 'gems', stats: { weapon: '+2 Cold DMG', shield: '+2 Cold Resist', armor: '+10 Max Mana' } },
	'sapphire': { name: 'Sapphire', w: 1, h: 1, color: 'bg-blue-600', type: 'gem', category: 'gems', stats: { weapon: '+3 Cold DMG', shield: '+3 Cold Resist', armor: '+15 Max Mana' } },
	'flawless_sapphire': { name: 'Flawless Sapphire', w: 1, h: 1, color: 'bg-blue-700', type: 'gem', category: 'gems', stats: { weapon: '+4 Cold DMG', shield: '+4 Cold Resist', armor: '+20 Max Mana' } },
	'perfect_sapphire': { name: 'Perfect Sapphire', w: 1, h: 1, color: 'bg-blue-800', type: 'gem', category: 'gems', stats: { weapon: '+5 Cold DMG', shield: '+5 Cold Resist', armor: '+25 Max Mana' } },
	'chipped_skull': { name: 'Chipped Skull', w: 1, h: 1, color: 'bg-gray-300', type: 'gem', category: 'gems', stats: { weapon: '+1 Life/Mana Steal', shield: '+1 Thorns', armor: '+1 Replenish HP & Mana' } },
	'flawed_skull': { name: 'Flawed Skull', w: 1, h: 1, color: 'bg-gray-400', type: 'gem', category: 'gems', stats: { weapon: '+2 Life/Mana Steal', shield: '+2 Thorns', armor: '+2 Replenish HP & Mana' } },
	'skull': { name: 'Skull', w: 1, h: 1, color: 'bg-gray-500', type: 'gem', category: 'gems', stats: { weapon: '+3 Life/Mana Steal', shield: '+3 Thorns', armor: '+3 Replenish HP & Mana' } },
	'flawless_skull': { name: 'Flawless Skull', w: 1, h: 1, color: 'bg-gray-600', type: 'gem', category: 'gems', stats: { weapon: '+4 Life/Mana Steal', shield: '+4 Thorns', armor: '+4 Replenish HP & Mana' } },
	'perfect_skull': { name: 'Perfect Skull', w: 1, h: 1, color: 'bg-gray-700', type: 'gem', category: 'gems', stats: { weapon: '+5 Life/Mana Steal', shield: '+5 Thorns', armor: '+5 Replenish HP & Mana' } },
	'chipped_topaz': { name: 'Chipped Topaz', w: 1, h: 1, color: 'bg-yellow-400', type: 'gem', category: 'gems', stats: { weapon: '+1 Lightning DMG', shield: '+1 Lightning Resist', armor: '+1 Magic Find' } },
	'flawed_topaz': { name: 'Flawed Topaz', w: 1, h: 1, color: 'bg-yellow-500', type: 'gem', category: 'gems', stats: { weapon: '+2 Lightning DMG', shield: '+2 Lightning Resist', armor: '+2 Magic Find' } },
	'topaz': { name: 'Topaz', w: 1, h: 1, color: 'bg-yellow-600', type: 'gem', category: 'gems', stats: { weapon: '+3 Lightning DMG', shield: '+3 Lightning Resist', armor: '+3 Magic Find' } },
	'flawless_topaz': { name: 'Flawless Topaz', w: 1, h: 1, color: 'bg-yellow-700', type: 'gem', category: 'gems', stats: { weapon: '+4 Lightning DMG', shield: '+4 Lightning Resist', armor: '+4 Magic Find' } },
	'perfect_topaz': { name: 'Perfect Topaz', w: 1, h: 1, color: 'bg-yellow-800', type: 'gem', category: 'gems', stats: { weapon: '+5 Lightning DMG', shield: '+5 Lightning Resist', armor: '+5 Magic Find' } },
	
	//Boots
	'boots': { name: 'Boots', w: 2, h: 2, color: 'bg-yellow-900', type: 'feet', category: 'boots', stats: { ac: 1, weight: 'Light' } },
	'heavy_boots': { name: 'Heavy Boots', w: 2, h: 2, color: 'bg-yellow-800', type: 'feet', category: 'boots', stats: { ac: 1, weight: 'Medium' } },
	'chain_boots': { name: 'Chain Boots', w: 2, h: 2, color: 'bg-gray-500', type: 'feet', category: 'boots', stats: { ac: 2, weight: 'Medium' } },
	'light_plated_boots': { name: 'Light Plated Boots', w: 2, h: 2, color: 'bg-gray-400', type: 'feet', category: 'boots', stats: { ac: 2, weight: 'Heavy' } },
	'greaves': { name: 'Greaves', w: 2, h: 2, color: 'bg-gray-300', type: 'feet', category: 'boots', stats: { ac: 3, weight: 'Heavy' } },
	
	//Gloves
	'leather_gloves': { name: 'Leather Gloves', w: 2, h: 2, color: 'bg-yellow-800', type: 'hands', category: 'gloves', stats: { ac: 1, weight: 'Light' } },
	'chain_gloves': { name: 'Chain Gloves', w: 2, h: 2, color: 'bg-gray-500', type: 'hands', category: 'gloves', stats: { ac: 2, weight: 'Light' } },
	'heavy_gloves': { name: 'Heavy Gloves', w: 2, h: 2, color: 'bg-yellow-900', type: 'hands', category: 'gloves', stats: { ac: 2, weight: 'Medium' } },
	'light_gauntlets': { name: 'Light Gauntlets', w: 2, h: 2, color: 'bg-gray-400', type: 'hands', category: 'gloves', stats: { ac: 3, weight: 'Medium' } },
	'gauntlets': { name: 'Gauntlets', w: 2, h: 2, color: 'bg-gray-600', type: 'hands', category: 'gloves', stats: { ac: 4, weight: 'Heavy' } },
	
	//Belts
	'sash': { name: 'Sash', w: 2, h: 1, color: 'bg-amber-200', type: 'belt', category: 'belts', stats: { ac: 1, cap: 4 } },
	'light_belt': { name: 'Light Belt', w: 2, h: 1, color: 'bg-slate-300', type: 'belt', category: 'belts', stats: { ac: 1, cap: 8 } },
	'belt': { name: 'Belt', w: 2, h: 1, color: 'bg-amber-600', type: 'belt', category: 'belts', stats: { ac: 2, cap: 8 } },
	'heavy_belt': { name: 'Heavy Belt', w: 2, h: 1, color: 'bg-amber-800', type: 'belt', category: 'belts', stats: { ac: 2, cap: 12 } },
	'plated_belt': { name: 'Plated Belt', w: 2, h: 1, color: 'bg-slate-500', type: 'belt', category: 'belts', stats: { ac: 3, cap: 16 } },
	
	// Jewelry
	'gold_ring': { name: 'Gold Ring', w: 1, h: 1, color: 'bg-amber-400', type: 'ring', category: 'jewelry', stats: {} },
	'silver_ring': { name: 'Silver Ring', w: 1, h: 1, color: 'bg-slate-300', type: 'ring', category: 'jewelry', stats: {} },
	'platinum_ring': { name: 'Platinum Ring', w: 1, h: 1, color: 'bg-neutral-500', type: 'ring', category: 'jewelry', stats: {} },
	'amulet_a': { name: 'Amulet', w: 1, h: 1, color: 'bg-red-500', type: 'necklace', category: 'jewelry', stats: {} },
	'amulet_b': { name: 'Amulet', w: 1, h: 1, color: 'bg-red-500', type: 'necklace', category: 'jewelry', stats: {} },
	'amulet_c': { name: 'Amulet', w: 1, h: 1, color: 'bg-red-500', type: 'necklace', category: 'jewelry', stats: {} },
	'jewel_a': { name: 'Jewel', w: 1, h: 1, color: 'bg-cyan-400', type: 'jewel', category: 'jewelry', stats: {} },
	'jewel_b': { name: 'Jewel', w: 1, h: 1, color: 'bg-violet-500', type: 'jewel', category: 'jewelry', stats: {} },
	'jewel_c': { name: 'Jewel', w: 1, h: 1, color: 'bg-green-500', type: 'jewel', category: 'jewelry', stats: {} },
	
	// Charms
	'charm_small_a': { name: 'Charm', w: 1, h: 1, color: 'bg-orange-200', type: 'charm', category: 'charms', stats: {} },
	'charm_small_b': { name: 'Charm', w: 1, h: 1, color: 'bg-orange-300', type: 'charm', category: 'charms', stats: {} },
	'charm_small_c': { name: 'Charm', w: 1, h: 1, color: 'bg-orange-400', type: 'charm', category: 'charms', stats: {} },
	'charm_medium_a': { name: 'Charm', w: 1, h: 2, color: 'bg-amber-200', type: 'charm', category: 'charms', stats: {} },
	'charm_medium_b': { name: 'Charm', w: 1, h: 2, color: 'bg-amber-300', type: 'charm', category: 'charms', stats: {} },
	'charm_medium_c': { name: 'Charm', w: 1, h: 2, color: 'bg-amber-400', type: 'charm', category: 'charms', stats: {} },
	'charm_large_a': { name: 'Charm', w: 1, h: 3, color: 'bg-yellow-200', type: 'charm', category: 'charms', stats: {} },
	'charm_large_b': { name: 'Charm', w: 1, h: 3, color: 'bg-yellow-300', type: 'charm', category: 'charms', stats: {} },
	'charm_large_c': { name: 'Charm', w: 1, h: 3, color: 'bg-yellow-400', type: 'charm', category: 'charms', stats: {} },
};
const CELL_SIZE = 40; const GAP_SIZE = 1; const GRID_COLS = 8; const GRID_ROWS = 6;